# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics_metadata.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'analytics_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61nalytics_metadata.proto\x12\x0fhailo_analytics\">\n\x04\x42\x62ox\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\"A\n\x0e\x43lassification\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"`\n\tLandmarks\x12\x15\n\rpoints_format\x18\x01 \x01(\t\x12\x15\n\rpoints_stride\x18\x02 \x01(\r\x12\x12\n\x06points\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x11\n\x05pairs\x18\x04 \x03(\rB\x02\x10\x01\"\x96\x02\n\tDetection\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12#\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x15.hailo_analytics.Bbox\x12\x18\n\x0btracking_id\x18\x04 \x01(\rH\x00\x88\x01\x01\x12.\n\ndetections\x18\x05 \x03(\x0b\x32\x1a.hailo_analytics.Detection\x12-\n\tlandmarks\x18\x06 \x03(\x0b\x32\x1a.hailo_analytics.Landmarks\x12\x38\n\x0f\x63lassifications\x18\x07 \x03(\x0b\x32\x1f.hailo_analytics.ClassificationB\x0e\n\x0c_tracking_id\"\xe5\x01\n\x05\x46rame\x12\x18\n\x10isp_timestamp_ns\x18\x01 \x01(\x04\x12\x13\n\x0b\x66rame_width\x18\x02 \x01(\r\x12\x14\n\x0c\x66rame_height\x18\x03 \x01(\r\x12.\n\ndetections\x18\x04 \x03(\x0b\x32\x1a.hailo_analytics.Detection\x12-\n\tlandmarks\x18\x05 \x03(\x0b\x32\x1a.hailo_analytics.Landmarks\x12\x38\n\x0f\x63lassifications\x18\x06 \x03(\x0b\x32\x1f.hailo_analytics.ClassificationB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LANDMARKS'].fields_by_name['points']._loaded_options = None
  _globals['_LANDMARKS'].fields_by_name['points']._serialized_options = b'\020\001'
  _globals['_LANDMARKS'].fields_by_name['pairs']._loaded_options = None
  _globals['_LANDMARKS'].fields_by_name['pairs']._serialized_options = b'\020\001'
  _globals['_BBOX']._serialized_start=45
  _globals['_BBOX']._serialized_end=107
  _globals['_CLASSIFICATION']._serialized_start=109
  _globals['_CLASSIFICATION']._serialized_end=174
  _globals['_LANDMARKS']._serialized_start=176
  _globals['_LANDMARKS']._serialized_end=272
  _globals['_DETECTION']._serialized_start=275
  _globals['_DETECTION']._serialized_end=553
  _globals['_FRAME']._serialized_start=556
  _globals['_FRAME']._serialized_end=785
# @@protoc_insertion_point(module_scope)
