#!/bin/bash
set -e

# Install script for drone-follow
# Installs: hailo-apps Python package (editable), drone-follow Python package
# (editable), and the UI.
#
# Prerequisites (one-time system setup, NOT done by this script):
#   - HailoRT and TAPPAS .deb + .whl packages installed (Hailo Developer Zone)
#   - /usr/local/hailo/resources/ populated with HEF models
#   - hailo-apps C++ postprocess modules compiled
# On a fresh machine, run `sudo hailo-apps/install.sh` ONCE to do all of the
# above; afterwards only this script is needed to (re)build the Python env
# and UI.
#
# Expects hailo-apps to be cloned inside the project directory (./hailo-apps).
# Override with --hailo-apps-dir or HAILO_APPS_DIR env var. If the checkout
# doesn't exist, it will be cloned (required since hailo-apps is an editable
# Python dep of this project).
#
# Usage: ./install.sh [OPTIONS]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Defaults
HAILO_APPS_DIR="${HAILO_APPS_DIR:-$SCRIPT_DIR/hailo-apps}"
SKIP_UI=false
SKIP_PYTHON=false

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --hailo-apps-dir DIR   Path to hailo-apps checkout (default: ./hailo-apps)"
    echo "  --skip-ui              Skip UI npm install and build"
    echo "  --skip-python          Skip Python venv + dependency installation"
    echo "  --help, -h             Show this help message"
    echo ""
    echo "Environment variables:"
    echo "  HAILO_APPS_DIR         Same as --hailo-apps-dir"
}

while [[ $# -gt 0 ]]; do
    case $1 in
        --hailo-apps-dir)   HAILO_APPS_DIR="$2"; shift 2 ;;
        --hailo-apps-dir=*) HAILO_APPS_DIR="${1#*=}"; shift ;;
        --skip-ui)          SKIP_UI=true; shift ;;
        --skip-python)      SKIP_PYTHON=true; shift ;;
        --help|-h)          usage; exit 0 ;;
        *)                  echo -e "${RED}Unknown argument: $1${NC}"; usage; exit 1 ;;
    esac
done

echo "========================================="
echo "  drone-follow installer"
echo "========================================="
echo ""

# ─── Step 1: Ensure hailo-apps checkout exists ───────────────────────
# hailo-apps is installed as an editable Python dep in Step 2, so the checkout
# must exist regardless of whether its system installer has been run.
echo -e "${GREEN}[1/3] Resolving hailo-apps checkout...${NC}"
if [ ! -d "$HAILO_APPS_DIR" ]; then
    echo -e "${YELLOW}  hailo-apps not found at: $HAILO_APPS_DIR${NC}"
    echo -e "  Cloning hailo-apps from github (branch: dev)..."
    git clone -b dev https://github.com/hailocs/hailo-apps-internal.git "$HAILO_APPS_DIR"
fi
HAILO_APPS_DIR="$(cd "$HAILO_APPS_DIR" && pwd)"
echo -e "  Using hailo-apps at: ${CYAN}$HAILO_APPS_DIR${NC}"

# ─── Step 2: Build repo-owned venv and install Python deps ───────────
REPO_VENV_DIR="$SCRIPT_DIR/venv"

if ! $SKIP_PYTHON; then
    echo -e "${GREEN}[2/3] Setting up repo Python venv at ${CYAN}$REPO_VENV_DIR${NC}..."

    if [ ! -d "$REPO_VENV_DIR" ]; then
        python3 -m venv --system-site-packages "$REPO_VENV_DIR"
        echo -e "  Created venv (--system-site-packages so apt-installed Hailo bindings are visible)."
    else
        echo -e "  Reusing existing venv."
    fi

    # shellcheck disable=SC1091
    source "$REPO_VENV_DIR/bin/activate"

    pip install --upgrade pip setuptools wheel

    echo -e "  Installing hailo-apps (editable)..."
    pip install -e "$HAILO_APPS_DIR"

    echo -e "  Installing drone-follow (editable)..."
    pip install -e "$SCRIPT_DIR"

    echo -e "${GREEN}  drone-follow + hailo-apps installed into $REPO_VENV_DIR.${NC}"
else
    echo -e "${YELLOW}[2/3] Skipping Python dependencies (--skip-python)${NC}"
fi

# ─── Step 3: Install and build UI ────────────────────────────────────
if ! $SKIP_UI; then
    echo -e "${GREEN}[3/3] Installing and building UI...${NC}"

    UI_DIR="$SCRIPT_DIR/drone_follow/ui"
    if [ ! -f "$UI_DIR/package.json" ]; then
        echo -e "${YELLOW}  No package.json found, skipping UI.${NC}"
    else
        if ! command -v npm &> /dev/null; then
            echo -e "${RED}  Error: npm is not installed. Install Node.js first:${NC}"
            echo -e "    sudo apt install nodejs npm"
            exit 1
        fi

        echo -e "  Running npm install..."
        (cd "$UI_DIR" && npm install)

        echo -e "  Building UI..."
        (cd "$UI_DIR" && npm run build)

        echo -e "${GREEN}  UI built successfully.${NC}"
    fi
else
    echo -e "${YELLOW}[3/3] Skipping UI installation (--skip-ui)${NC}"
fi

# ─── Regenerate setup_env.sh ─────────────────────────────────────────
cat > "$SCRIPT_DIR/setup_env.sh" << 'SETUP_EOF'
#!/bin/bash
# Auto-generated by install.sh. Activates the repo-owned venv, sets PYTHONPATH,
# runs the RPi kernel-compatibility check, and loads /usr/local/hailo/resources/.env.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/venv"

# RPi kernel-version check (mirrors hailo-apps/setup_env.sh)
if uname -a | grep -q "Linux raspberrypi"; then
    INVALID_KERNELS=("6.12.21" "6.12.22" "6.12.23" "6.12.24" "6.12.25")
    CURRENT_VERSION=$(uname -r | cut -d '+' -f 1)
    for k in "${INVALID_KERNELS[@]}"; do
        if [ "$k" = "$CURRENT_VERSION" ]; then
            echo "Error: Kernel $CURRENT_VERSION is incompatible." >&2
            echo "See https://community.hailo.ai/t/raspberry-pi-kernel-compatibility-issue-temporary-fix/15322" >&2
            return 1
        fi
    done
fi

export PYTHONPATH="$SCRIPT_DIR:$PYTHONPATH"

if [ -d "$VENV_DIR" ]; then
    # shellcheck disable=SC1091
    source "$VENV_DIR/bin/activate"
    echo "Activated venv at $VENV_DIR"
else
    echo "Error: venv not found at $VENV_DIR. Run ./install.sh first." >&2
    return 1
fi

ENV_FILE="/usr/local/hailo/resources/.env"
if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r key value; do
        [[ -z "$key" || "$key" =~ ^# ]] && continue
        export "$key=$value"
        upper_key=$(echo "$key" | tr '[:lower:]' '[:upper:]')
        export "$upper_key=$value"
    done < "$ENV_FILE"
fi
SETUP_EOF
chmod +x "$SCRIPT_DIR/setup_env.sh"

echo ""
echo -e "${GREEN}Installation complete!${NC}"
echo ""
echo "Next steps:"
echo "  source setup_env.sh"
echo "  drone-follow --input rpi --ui"
