"""ZMQ subscriber that bridges the C++ native_pipeline binary to the
Python orchestrator.

Replaces the heavy ``_run_inference`` loop in
``pipeline_adapter/hailo15_pipeline.py``. Workflow:

    C++ binary (df_native_pipeline)
        ↓ protobuf Frame over ZMQ pub
    NativePipelineSubscriber (this module)
        ├─ filter to person detections, normalize bboxes
        ├─ ByteTracker.update → stable IDs
        ├─ pick the followed target (target_state or largest-by-area)
        ├─ SharedDetectionState.update → control loop reads from here
        └─ SharedUIState.update_detections(commit=True) → web UI bboxes

The C++ pipeline owns the ISP/inference; Python owns the tracker, the
web UI / follow server, and the drone control loop. Native mode does
NOT push JPEG frames into the UI (the C++ pipeline emits H264 over UDP,
viewable via analytic_viewer); the UI shows live bbox overlays only,
with an empty video layer.
"""

from __future__ import annotations

import logging
import threading
import time
import types
from typing import Optional

import numpy as np
import zmq


def _ensure_protobuf_runtime_version() -> None:
    """Stub ``google.protobuf.runtime_version`` if absent.

    Our analytics_metadata_pb2.py is generated by a modern protoc that
    imports runtime_version (protobuf 5.x+). The H15 Yocto image ships
    protobuf 3.20.3 which doesn't have it. Stubbing is enough — the
    runtime checks are no-ops when the module just exposes the
    expected names.
    """
    import google.protobuf as _gp
    if hasattr(_gp, "runtime_version"):
        return
    stub = types.ModuleType("runtime_version")
    stub.__version__ = (5, 0, 0)
    stub.check = lambda *_a, **_kw: None
    stub.ValidateProtobufRuntimeVersion = lambda *_a, **_kw: None
    stub.Domain = type("Domain", (), {"PUBLIC": 1})()
    _gp.runtime_version = stub  # type: ignore[attr-defined]


_ensure_protobuf_runtime_version()

from robot_follow.follow_api.state import SharedDetectionState, FollowTargetState  # noqa: E402
from robot_follow.follow_api.types import Detection  # noqa: E402
from robot_follow.native_pipeline.protos import analytics_metadata_pb2 as _pb  # noqa: E402

LOGGER = logging.getLogger(__name__)

PERSON_LABEL = "person"
DETECTION_CONFIDENCE_THRESHOLD = 0.4


class NativePipelineSubscriber:
    """Background thread that consumes detections from the native pipeline.

    Args:
        shared_state: receives the single followed-target detection +
            the set of currently-tracked IDs. The control loop reads
            from here.
        zmq_endpoint: where the C++ binary's pub socket is bound. When
            the binary runs on the same H15 as this subscriber, use
            ``tcp://127.0.0.1:7000``.
        byte_tracker: optional ``ByteTracker`` instance for stable IDs.
            When ``None``, raw detections are forwarded with synthesized
            per-frame integer IDs (good enough for one-shot tests).
        target_state: optional ``FollowTargetState``. When provided, the
            selected target's detection is preferred for ``follow_det``;
            otherwise the largest-area detection wins.
        ui_state: optional ``SharedUIState``. When provided, every frame's
            detections are forwarded with ``commit=True`` so the web UI's
            SSE stream wakes up even though native mode never produces a
            JPEG.
    """

    def __init__(
        self,
        shared_state: SharedDetectionState,
        *,
        zmq_endpoint: str = "tcp://127.0.0.1:7000",
        byte_tracker=None,
        target_state: Optional[FollowTargetState] = None,
        ui_state=None,
        record_path: Optional[str] = None,
        tiles: Optional[list] = None,
    ) -> None:
        self._shared_state = shared_state
        self._target_state = target_state
        self._ui_state = ui_state
        self._byte_tracker = byte_tracker
        self._zmq_endpoint = zmq_endpoint
        self._stop_event = threading.Event()
        self._thread: Optional[threading.Thread] = None
        self._frame_count = 0
        # Active tile list (used for attribution stats). None → fall back to
        # DEFAULT_TILES. Each entry is (name, x, y, w, h).
        self._tiles = tiles if tiles else list(DEFAULT_TILES)
        # Public read-only stats.
        self.last_frame_ts: Optional[float] = None
        # Detection .jsonl sidecar (same path convention as the old
        # hailo15_pipeline.py: <record_path>.mkv → <record_path>.jsonl).
        # Lets the post-process overlay script keep working unchanged.
        self._det_log = None
        self._det_log_t0: Optional[float] = None
        if record_path:
            import os
            log_path = record_path.rsplit(".", 1)[0] + ".jsonl"
            os.makedirs(os.path.dirname(log_path) or ".", exist_ok=True)
            self._det_log = open(log_path, "w", buffering=1)
            LOGGER.info("[zmq] Detection log: %s", log_path)
            # Header line: active tile configuration. post-process reads
            # this to bake the matching tile overlay into the annotated
            # mp4. Skipped if open() failed silently. Keyed by "_header"
            # so loader can distinguish it from per-frame records.
            try:
                import json as _json
                self._det_log.write(_json.dumps({
                    "_header": True,
                    "tiles": [{"name": n, "x": x, "y": y, "w": w, "h": h}
                              for (n, x, y, w, h) in self._tiles],
                }) + "\n")
            except Exception:
                LOGGER.warning("[zmq] failed to write det log header", exc_info=True)

    # ------------------------------------------------------------------ #
    # Lifecycle
    # ------------------------------------------------------------------ #
    def start(self) -> None:
        if self._thread is not None:
            return
        self._stop_event.clear()
        self._thread = threading.Thread(
            target=self._run,
            name="native-zmq-subscriber",
            daemon=True,
        )
        self._thread.start()
        LOGGER.info("[zmq] subscribing on %s", self._zmq_endpoint)

    def stop(self, timeout: float = 2.0) -> None:
        self._stop_event.set()
        if self._thread is not None:
            self._thread.join(timeout=timeout)
            self._thread = None
        if self._det_log is not None:
            try:
                self._det_log.close()
            except Exception:
                pass
            self._det_log = None

    def set_tiles(self, new_tiles: list) -> None:
        """Replace the active tile list used for per-frame attribution
        stats. Called by the orchestrator's hot-swap path so the stats
        line up with what the C++ DynamicTilingCropStage just swapped
        to. Assignment of a fresh list is atomic in CPython (GIL), so no
        explicit lock is needed against the subscriber's worker thread.
        """
        self._tiles = list(new_tiles)

    def _write_det_log(self, ui_dets: list, target_id: Optional[int]) -> None:
        """Append a per-frame JSONL record with the same shape the old
        hailo15_pipeline.py wrote, so post_process/overlay_detections.py
        keeps working unchanged."""
        if self._det_log is None:
            return
        import json as _json
        if self._det_log_t0 is None:
            self._det_log_t0 = time.monotonic()
        t_rel = time.monotonic() - self._det_log_t0
        rec = {
            "t": round(t_rel, 4),
            "following_id": target_id,
            "detections": ui_dets,
        }
        try:
            self._det_log.write(_json.dumps(rec) + "\n")
        except Exception:
            LOGGER.warning("[zmq] det log write failed", exc_info=True)

    @property
    def frame_count(self) -> int:
        return self._frame_count

    # ------------------------------------------------------------------ #
    # Internal
    # ------------------------------------------------------------------ #
    def _run(self) -> None:
        ctx = zmq.Context.instance()
        sock = ctx.socket(zmq.SUB)
        sock.connect(self._zmq_endpoint)
        sock.setsockopt(zmq.SUBSCRIBE, b"")
        # Short recv timeout so we can poll _stop_event periodically.
        sock.setsockopt(zmq.RCVTIMEO, 500)
        try:
            while not self._stop_event.is_set():
                try:
                    raw = sock.recv()
                except zmq.Again:
                    continue
                self._frame_count += 1
                try:
                    self._handle_frame(raw)
                except Exception:
                    LOGGER.warning("[zmq] error handling frame %d",
                                   self._frame_count, exc_info=True)
        finally:
            sock.close(linger=0)

    def _handle_frame(self, raw: bytes) -> None:
        frame = _pb.Frame()
        frame.ParseFromString(raw)
        if frame.frame_width <= 0 or frame.frame_height <= 0:
            return
        self.last_frame_ts = time.monotonic()

        detections = _normalize_person_detections(frame)

        if self._byte_tracker is not None and detections:
            track_by_id, ui_dets = _track_detections(self._byte_tracker, detections)
        else:
            track_by_id = {i: d for i, d in enumerate(detections)}
            ui_dets = [_detection_to_ui_dict(d, i) for i, d in enumerate(detections)]
        tracked_ids = set(track_by_id.keys())

        # Select the followed detection: target_state's pick if available,
        # else largest area × confidence. Matches the legacy semantics in
        # hailo15_pipeline.py:730-737.
        target_id = self._target_state.get_target() if self._target_state else None
        if target_id is not None and target_id in track_by_id:
            follow_det = track_by_id[target_id]
        elif track_by_id:
            follow_det = max(
                track_by_id.values(),
                key=lambda d: d.bbox_height * d.confidence,
            )
        else:
            follow_det = None

        self._shared_state.update(follow_det, available_ids=tracked_ids)
        self._write_det_log(ui_dets, target_id=(
            self._target_state.get_target() if self._target_state else None))

        # Per-frame stats for tiling verification. We attribute each
        # detection to the smallest active tile (self._tiles) it fully
        # fits inside — small bboxes contained in quadrant tiles are
        # evidence the tiling DSP crop fired (a full-frame inference would
        # downsample them below YOLOv8s's detection floor).
        stats = _compute_tile_stats(ui_dets, self._tiles)

        if self._ui_state is not None:
            following_id = (
                self._target_state.get_target() if self._target_state else None
            )
            # commit=True advances _frame_seq so the SSE handler wakes up.
            # Without it the UI never sees new detections because its SSE
            # stream blocks on the seq counter (designed around the Python
            # pipeline that pairs each JPEG with detections).
            self._ui_state.update_detections(
                ui_dets, following_id=following_id, commit=True, stats=stats,
            )

        # Periodic log line every ~30 frames (~2 s at 15 fps). Lets the
        # user watch tile activity from the H15 console too, not just UI.
        if self._frame_count % 30 == 0:
            LOGGER.info(
                "[tiling] frame=%d total=%d smallest=%.3f×%.3f per_tile=%s",
                self._frame_count,
                stats["count"],
                stats["smallest_w"],
                stats["smallest_h"],
                stats["per_tile"],
            )


# ---------------------------------------------------------------------- #
# Pure helpers — no I/O, no instance state. Easier to unit-test.
# ---------------------------------------------------------------------- #

def _normalize_person_detections(frame) -> list[Detection]:
    """Convert protobuf Detection (pixel coords, multi-class) to the
    project's Detection (normalized coords, person-only)."""
    out: list[Detection] = []
    fw = float(frame.frame_width)
    fh = float(frame.frame_height)
    now = time.monotonic()
    for det in frame.detections:
        if det.label != PERSON_LABEL:
            continue
        if det.confidence < DETECTION_CONFIDENCE_THRESHOLD:
            continue
        bb = det.bbox
        bw = (bb.xmax - bb.xmin) / fw
        bh = (bb.ymax - bb.ymin) / fh
        cx = (bb.xmin + bb.xmax) / 2.0 / fw
        cy = (bb.ymin + bb.ymax) / 2.0 / fh
        out.append(Detection(
            label="person",
            confidence=float(det.confidence),
            center_x=cx,
            center_y=cy,
            bbox_height=bh,
            bbox_width=bw,
            timestamp=now,
        ))
    return out


def _track_detections(byte_tracker, detections: list[Detection]):
    """Run ByteTracker, IoU-match each track back to a raw detection so
    UI bboxes are pixel-accurate, and return (track_by_id, ui_dets).
    Mirrors the loop in hailo15_pipeline.py:670-712."""
    tlbr_score = np.array([
        [d.center_x - d.bbox_width / 2,
         d.center_y - d.bbox_height / 2,
         d.center_x + d.bbox_width / 2,
         d.center_y + d.bbox_height / 2,
         d.confidence]
        for d in detections
    ])
    tracks = byte_tracker.update(tlbr_score, (1, 1))
    track_by_id: dict[int, Detection] = {}
    ui_dets: list[dict] = []
    for t in tracks:
        tx1, ty1, tx2, ty2 = t.tlbr
        best_iou, best_det = 0.0, None
        for d in detections:
            dx1 = d.center_x - d.bbox_width / 2
            dy1 = d.center_y - d.bbox_height / 2
            dx2 = d.center_x + d.bbox_width / 2
            dy2 = d.center_y + d.bbox_height / 2
            ix1 = max(tx1, dx1); iy1 = max(ty1, dy1)
            ix2 = min(tx2, dx2); iy2 = min(ty2, dy2)
            inter = max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)
            union = ((tx2 - tx1) * (ty2 - ty1) +
                     (dx2 - dx1) * (dy2 - dy1) - inter)
            iou = inter / union if union > 0 else 0.0
            if iou > best_iou:
                best_iou, best_det = iou, d
        if best_det is not None and best_iou > 0.2:
            raw = best_det
            x1 = raw.center_x - raw.bbox_width / 2
            y1 = raw.center_y - raw.bbox_height / 2
            bw = raw.bbox_width
            bh = raw.bbox_height
        else:
            x1, y1 = tx1, ty1
            bw, bh = tx2 - tx1, ty2 - ty1
        tid = int(t.track_id)
        track_by_id[tid] = Detection(
            label="person",
            confidence=float(t.score),
            center_x=x1 + bw / 2,
            center_y=y1 + bh / 2,
            bbox_height=bh,
            bbox_width=bw,
            timestamp=time.monotonic(),
        )
        ui_dets.append({
            "id": tid,
            "bbox": {"x": x1, "y": y1, "w": bw, "h": bh},
            "confidence": float(t.score),
            "label": "person",
        })
    return track_by_id, ui_dets


def _detection_to_ui_dict(d: Detection, det_id: int) -> dict:
    return {
        "id": det_id,
        "bbox": {
            "x": d.center_x - d.bbox_width / 2,
            "y": d.center_y - d.bbox_height / 2,
            "w": d.bbox_width,
            "h": d.bbox_height,
        },
        "confidence": float(d.confidence),
        "label": d.label,
    }


# Must match hailo_analytics::analytics::tiling::DEFAULT_TILES (see
# tiling.hpp): four overlapping 60%×60% quadrants + one full-frame tile.
# (name, x, y, w, h) all normalized to frame. Used only for attribution —
# the actual tiling/cropping happens on the H15 DSP. The orchestrator may
# replace this list at runtime via the ``tiles=`` constructor arg.
DEFAULT_TILES = [
    ("TL",   0.0, 0.0, 0.6, 0.6),
    ("TR",   0.4, 0.0, 0.6, 0.6),
    ("BL",   0.0, 0.4, 0.6, 0.6),
    ("BR",   0.4, 0.4, 0.6, 0.6),
    ("FULL", 0.0, 0.0, 1.0, 1.0),
]


def _attribute_tile(bbox: dict, tiles: list) -> str:
    """Assign a detection to the smallest tile in ``tiles`` that fully
    contains its bbox. Smaller-area tiles beat larger ones, so a small
    bbox in the top-left quadrant registers as that quadrant even though
    a full-frame tile contains it too. Detections that fit no tile fully
    return "OUT" (only happens if the tile set doesn't cover the frame).
    """
    bx, by = bbox["x"], bbox["y"]
    bw, bh = bbox["w"], bbox["h"]
    bxe, bye = bx + bw, by + bh
    best_name, best_area = "OUT", float("inf")
    for name, tx, ty, tw, th in tiles:
        if bx >= tx and by >= ty and bxe <= tx + tw and bye <= ty + th:
            area = tw * th
            if area < best_area:
                best_name, best_area = name, area
    return best_name


def _compute_tile_stats(ui_dets: list, tiles: list) -> dict:
    """Per-frame summary used for tiling verification (UI badge + log)."""
    per_tile = {name: 0 for (name, *_) in tiles}
    per_tile["OUT"] = 0
    smallest_w = 1.0
    smallest_h = 1.0
    for det in ui_dets:
        bbox = det.get("bbox") or {}
        if not bbox:
            continue
        tile = _attribute_tile(bbox, tiles)
        per_tile[tile] = per_tile.get(tile, 0) + 1
        smallest_w = min(smallest_w, bbox.get("w", 1.0))
        smallest_h = min(smallest_h, bbox.get("h", 1.0))
    return {
        "count": len(ui_dets),
        "smallest_w": smallest_w if ui_dets else 0.0,
        "smallest_h": smallest_h if ui_dets else 0.0,
        "per_tile": per_tile,
    }


def parse_tiles_spec(spec: str) -> list:
    """Parse "x,y,w,h;x,y,w,h;..." → list of (name, x, y, w, h) tuples.

    Auto-names tiles as ``T0``, ``T1``, ... unless an explicit name is
    embedded as a ``name=x,y,w,h`` prefix. Mirrors the C++ side's parser
    (main.cpp:parse_tiles_spec): values in [0,1], at least 2 tiles, no
    out-of-bounds. Raises ValueError on malformed input.
    """
    out: list = []
    for i, raw in enumerate(spec.split(";")):
        raw = raw.strip()
        if not raw:
            continue
        name = f"T{i}"
        if "=" in raw:
            name, raw = raw.split("=", 1)
            name = name.strip()
            raw = raw.strip()
        parts = raw.split(",")
        if len(parts) != 4:
            raise ValueError(f"tile spec '{raw}' must have 4 fields, got {len(parts)}")
        try:
            x, y, w, h = (float(p) for p in parts)
        except ValueError as e:
            raise ValueError(f"tile spec '{raw}' has non-numeric field: {e}")
        for label, v in (("x", x), ("y", y), ("w", w), ("h", h)):
            if not 0.0 <= v <= 1.0:
                raise ValueError(f"tile spec '{raw}' field {label}={v} out of [0,1]")
        if w <= 0.0 or h <= 0.0:
            raise ValueError(f"tile spec '{raw}' has zero/negative width/height")
        if x + w > 1.0 + 1e-6 or y + h > 1.0 + 1e-6:
            raise ValueError(f"tile spec '{raw}' exceeds frame bounds")
        out.append((name, x, y, w, h))
    if len(out) < 2:
        raise ValueError("tiles spec needs at least 2 tiles "
                         f"(got {len(out)}); single-tile causes AI stage "
                         "to see zero buffers")
    return out


def tiles_to_spec(tiles: list) -> str:
    """Serialize a tile list to ``x,y,w,h;x,y,w,h;...`` for the C++ binary.
    Names are Python-side only (display + attribution stats); the C++ side
    parser takes coords only — see main.cpp:parse_tiles_spec."""
    return ";".join(f"{x},{y},{w},{h}" for (_n, x, y, w, h) in tiles)
