#!/bin/sh
### BEGIN INIT INFO
# Provides:          drone-follow
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hailo15 drone-follow application
### END INIT INFO

NAME=drone-follow
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/drone-follow.log
DEFAULTS=/etc/default/drone-follow

# Load configurable args (DRONE_FOLLOW_ARGS)
DRONE_FOLLOW_ARGS=""
[ -f $DEFAULTS ] && . $DEFAULTS

export PYTHONPATH=/home/root

case "$1" in
    start)
        echo "Starting $NAME (args: $DRONE_FOLLOW_ARGS)"
        cd /home/root
        start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
            --exec /bin/sh -- -c "exec /usr/bin/python3 -m robot_follow.drone_follow_h15 $DRONE_FOLLOW_ARGS >> $LOGFILE 2>&1"
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --stop --pidfile $PIDFILE --retry 10
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
            echo "$NAME is running (pid $(cat $PIDFILE))"
        else
            echo "$NAME is not running"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
